function Mostrar()
{

/*AL GENERAR NRO RAMDON DE 0 A 10 SE DEBE CONTAR LA CANTIDAD DE CADA UNA DE ESTAS CIFRAS, REPETIR LA INTERACION PARA LANZAR RANDOM 100.000 VECES

1-LA CANTIDAD DE VECES Q SALIO EL NRO DE 0 AL 10
2-EL PORSENTAJE DE VECES Q SALIO EL NRO CON RESPECTO AL TOTAL.
*/


}//FIN DE LA FUNCIÓN